### ISSUE TITLE
Error when running command

### ISSUE THREAD

**Issue by mqbui1** [noelportugal/google-home-notifier#1]
Hello,

This setup is running on a Raspberry PI 3.
In the example.js, I've set the following:

const serverPort = 8081;
var deviceName = 'Master Bedroom Home';

I then ran $ sudo node example.js.
But when I run the following command, there is no respond from my Google Home:
$ curl -X POST -d  "text=test" http://localhost:8081/google-home-notifier

If I run the command again, I receive the following error as indicated in the screenshot attached

![google-home-notification_error](https://cloud.githubusercontent.com/assets/3310707/21464682/271e2a9a-c93a-11e6-8c52-ace4501a108c.JPG)

Any help is appreciated, thanks.

**Comment by noelportugal** [comment]
Hello,
I tried with a fresh copy of raspbian jessie. I did the following:
sudo apt-get update
sudo apt-get upgrade

Then I made sure I had the latest nodejs distribution:
curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install nodejs

Installed required packages:
sudo apt-get install git-core libnss-mdns libavahi-compat-libdnssd-dev

Then I cloned the project and ran
npm install

Then modified vi node_modules/mdns/lib/browser.js as I documented in the README file.

And this works! I have updated the README to reflect the need for the latest nodejs.

Hope this solves your issue!

**Comment by destructure00** [comment]
Similar issue here. I followed all of the prerequisites you just posted above and still getting this error. First attempt gives an incomplete list of cast devices on my network. Second attempt produces the TypeError problem.

![image](https://cloud.githubusercontent.com/assets/19873190/21849608/d1f87636-d7c3-11e6-970a-8584fd858d80.png)

**Comment by destructure00** [comment]
I had to use the long name like "Google Home-lkansclc93980g8o3ngi89nisonvslkd" as the device name (instead of the friendly name Kitchen Home that I set up in the Home app) in example.js and it's working now.
